// ============================================================
// File: app/(root)/stakeholder/index.tsx
// Purpose: Institution Stakeholder View-Only Executive Dashboard
// Styled to match My Vidyon's authentic brand palette, theme, and cards
// ============================================================

import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  RefreshControl,
  Alert,
  Dimensions,
  Share,
} from 'react-native';
import { useAuth } from '../../../src/hooks/useAuth';
import { useRBAC } from '../../../src/hooks/useRBAC';
import { useStakeholderDashboard } from '../../../src/hooks/useStakeholderDashboard';
import { PageHeader } from '../../../src/components/common/PageHeader';
import { StatCard } from '../../../src/components/common/StatCard';
import { theme } from '../../../src/theme';
import {
  Building2,
  Users,
  GraduationCap,
  TrendingUp,
  Download,
  ShieldCheck,
  Eye,
  Calendar,
  DollarSign,
  ChevronDown,
  CheckCircle,
  BarChart3,
  Award,
  Layers,
  Sparkles,
  Wifi,
  CreditCard,
  CheckSquare,
  UserCheck,
  BookOpen,
  School,
  Clock,
} from 'lucide-react-native';

const { width: screenWidth } = Dimensions.get('window');

export default function StakeholderDashboard() {
  const { fullName, role, imageUrl, signOut, institutionName: authInstName, institutionLogo: authInstLogo } = useAuth();
  const {
    linkedInstitutions,
    currentInstitutionId,
    currentInstitution,
    setCurrentInstitutionId,
  } = useRBAC();

  const {
    metrics,
    institutionBreakdown,
    loading,
    refreshing,
    onRefresh,
  } = useStakeholderDashboard();

  const [activeTab, setActiveTab] = useState<'overview' | 'financials' | 'academics' | 'institutions'>('overview');
  const [showInstitutionSelector, setShowInstitutionSelector] = useState(false);

  // Formatter for Indian Rupees currency
  const formatCurrency = (amount: number) => {
    if (amount >= 10000000) {
      return `₹${(amount / 10000000).toFixed(2)} Cr`;
    }
    if (amount >= 100000) {
      return `₹${(amount / 100000).toFixed(2)} L`;
    }
    return '₹' + (amount || 0).toLocaleString('en-IN');
  };

  // Export report function
  const handleExport = async () => {
    const institutionTitle = currentInstitution
      ? currentInstitution.name
      : linkedInstitutions.length > 1
      ? `All Linked Institutions (${linkedInstitutions.length})`
      : authInstName || 'My Vidyon Institution';

    const reportContent = `
=============================================
VIDYON ERP - STAKEHOLDER EXECUTIVE REPORT
=============================================
Scope: ${institutionTitle}
Generated At: ${new Date().toLocaleString()}
Generated By: ${fullName || 'Institution Stakeholder'}

--- EXECUTIVE SUMMARY ---
Total Students: ${metrics.totalStudents.toLocaleString()}
Total Faculty & Staff: ${metrics.totalFaculty.toLocaleString()}
Student Attendance Rate: ${metrics.attendanceRate}%
Academic Pass Rate: ${metrics.passPercentage}%
Average Grade: ${metrics.averageGrade}

--- FINANCIAL OVERVIEW ---
Total Fee Expected: ${formatCurrency(metrics.totalFeeExpected)}
Total Fee Collected: ${formatCurrency(metrics.totalFeeCollected)}
Total Fee Pending: ${formatCurrency(metrics.totalFeePending)}
Collection Efficiency: ${metrics.collectionRate}%

--- INSTITUTION COMPARISON ---
${institutionBreakdown
  .map(
    inst =>
      `• ${inst.institution_name}: ${inst.student_count} students, ${inst.attendance_percentage}% attendance, ${formatCurrency(inst.total_revenue_collected)} revenue`
  )
  .join('\n')}
=============================================
`.trim();

    try {
      await Share.share({
        title: `Vidyon Stakeholder Report - ${new Date().toISOString().split('T')[0]}`,
        message: reportContent,
      });
    } catch {
      Alert.alert('Report Exported', 'Stakeholder executive report generated successfully.');
    }
  };

  // Write action rejection demonstration
  const handleAttemptWrite = (actionName: string) => {
    Alert.alert(
      'Read-Only Access Restricted',
      `Institution Stakeholders have view-only privileges. Cannot perform "${actionName}". All write operations are protected at UI and database levels.`,
      [{ text: 'Understood' }]
    );
  };

  const selectedTitle = currentInstitution
    ? currentInstitution.name
    : linkedInstitutions.length > 1
    ? 'All Institutions (Aggregated Network)'
    : linkedInstitutions[0]?.name || authInstName || 'Linked Institution';

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.contentContainer}
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[theme.colors.primary]} />}
    >
      <View style={styles.responsiveContainer}>
        {/* Header Matching Vidyon Authentics */}
        <PageHeader
          title={fullName ? `Welcome, ${fullName}` : 'Welcome, Stakeholder'}
          subtitle="Executive Board Oversight & Strategic Governance"
          institutionName={currentInstitution?.name || authInstName || undefined}
          institutionLogo={currentInstitution?.logo_url || authInstLogo || undefined}
          userRole="institution_stakeholder"
          userAvatar={imageUrl || undefined}
          userSubtitle="Board Member / Trustee"
          actions={
            <View style={styles.headerActionsRow}>
              <View style={styles.liveBadge}>
                <Wifi size={12} color="#10B981" {...({} as any)} />
                <Text style={styles.liveBadgeText}>LIVE TELEMETRY</Text>
              </View>
              <TouchableOpacity style={styles.exportButton} onPress={handleExport} activeOpacity={0.8}>
                <Download size={15} color="#1E293B" {...({} as any)} />
                <Text style={styles.exportButtonText}>Export Report</Text>
              </TouchableOpacity>
            </View>
          }
        />

        {/* Stakeholder View-Only Banner - Warm Golden Brand Theme */}
        <View style={styles.bannerContainer}>
          <View style={styles.bannerIconWrapper}>
            <ShieldCheck size={22} color="#D97706" {...({} as any)} />
          </View>
          <View style={styles.bannerTextContainer}>
            <View style={styles.bannerTitleRow}>
              <Text style={styles.bannerTitle}>Institution Stakeholder Governance Mode</Text>
              <Sparkles size={14} color="#D97706" {...({} as any)} />
            </View>
            <Text style={styles.bannerSubtitle}>
              Continuous read-only telemetry across real-time academic quality, attendance feeds, and financial treasury.
            </Text>
          </View>
          <View style={styles.viewBadge}>
            <Eye size={12} color="#92400E" {...({} as any)} />
            <Text style={styles.viewBadgeText}>VIEW ONLY</Text>
          </View>
        </View>

        {/* Multi-Institution Selector Card */}
        {linkedInstitutions.length > 1 && (
          <View style={styles.selectorCard}>
            <View style={styles.selectorHeader}>
              <Layers size={14} color={theme.colors.secondary} {...({} as any)} />
              <Text style={styles.selectorLabel}>ACTIVE INSTITUTION SCOPE</Text>
            </View>
            <TouchableOpacity
              style={styles.selectorDropdown}
              activeOpacity={0.8}
              onPress={() => setShowInstitutionSelector(!showInstitutionSelector)}
            >
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 }}>
                <View style={styles.selectorIconBox}>
                  <Building2 size={18} color={theme.colors.secondary} {...({} as any)} />
                </View>
                <Text style={styles.selectorCurrentText} numberOfLines={1}>
                  {selectedTitle}
                </Text>
              </View>
              <ChevronDown size={18} color={theme.colors.textMuted} {...({} as any)} />
            </TouchableOpacity>

            {showInstitutionSelector && (
              <View style={styles.dropdownMenu}>
                <TouchableOpacity
                  style={[
                    styles.dropdownItem,
                    !currentInstitutionId && styles.dropdownItemActive,
                  ]}
                  onPress={() => {
                    setCurrentInstitutionId(null);
                    setShowInstitutionSelector(false);
                  }}
                >
                  <Text
                    style={[
                      styles.dropdownItemText,
                      !currentInstitutionId && styles.dropdownItemTextActive,
                    ]}
                  >
                    🌐 All Linked Institutions (Aggregated View)
                  </Text>
                  {!currentInstitutionId && <CheckCircle size={16} color={theme.colors.secondary} {...({} as any)} />}
                </TouchableOpacity>

                {linkedInstitutions.map(inst => (
                  <TouchableOpacity
                    key={inst.institution_id}
                    style={[
                      styles.dropdownItem,
                      currentInstitutionId === inst.institution_id && styles.dropdownItemActive,
                    ]}
                    onPress={() => {
                      setCurrentInstitutionId(inst.institution_id);
                      setShowInstitutionSelector(false);
                    }}
                  >
                    <Text
                      style={[
                        styles.dropdownItemText,
                        currentInstitutionId === inst.institution_id && styles.dropdownItemTextActive,
                      ]}
                    >
                      🏫 {inst.name}
                    </Text>
                    {currentInstitutionId === inst.institution_id && (
                      <CheckCircle size={16} color={theme.colors.secondary} {...({} as any)} />
                    )}
                  </TouchableOpacity>
                ))}
              </View>
            )}
          </View>
        )}

        {/* Tab Navigation - Matching Vidyon Warm Pill Style */}
        <View style={styles.tabsRow}>
          <TouchableOpacity
            style={[styles.tabButton, activeTab === 'overview' && styles.tabButtonActive]}
            onPress={() => setActiveTab('overview')}
            activeOpacity={0.8}
          >
            <TrendingUp size={16} color={activeTab === 'overview' ? '#1E293B' : theme.colors.textMuted} {...({} as any)} />
            <Text style={[styles.tabButtonText, activeTab === 'overview' && styles.tabButtonTextActive]}>Overview</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.tabButton, activeTab === 'financials' && styles.tabButtonActive]}
            onPress={() => setActiveTab('financials')}
            activeOpacity={0.8}
          >
            <CreditCard size={16} color={activeTab === 'financials' ? '#1E293B' : theme.colors.textMuted} {...({} as any)} />
            <Text style={[styles.tabButtonText, activeTab === 'financials' && styles.tabButtonTextActive]}>Financials</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.tabButton, activeTab === 'academics' && styles.tabButtonActive]}
            onPress={() => setActiveTab('academics')}
            activeOpacity={0.8}
          >
            <Award size={16} color={activeTab === 'academics' ? '#1E293B' : theme.colors.textMuted} {...({} as any)} />
            <Text style={[styles.tabButtonText, activeTab === 'academics' && styles.tabButtonTextActive]}>Academics</Text>
          </TouchableOpacity>
          {linkedInstitutions.length > 1 && (
            <TouchableOpacity
              style={[styles.tabButton, activeTab === 'institutions' && styles.tabButtonActive]}
              onPress={() => setActiveTab('institutions')}
              activeOpacity={0.8}
            >
              <Building2 size={16} color={activeTab === 'institutions' ? '#1E293B' : theme.colors.textMuted} {...({} as any)} />
              <Text style={[styles.tabButtonText, activeTab === 'institutions' && styles.tabButtonTextActive]}>Comparison</Text>
            </TouchableOpacity>
          )}
        </View>

        {/* TAB 1: OVERVIEW */}
        {activeTab === 'overview' && (
          <View style={styles.tabContent}>
            <Text style={styles.sectionHeader}>Key Performance Indicators</Text>
            <View style={styles.statsGrid}>
              <StatCard
                title="Total Enrollment"
                value={metrics.totalStudents.toLocaleString()}
                icon={Users}
                iconColor="#F59E0B"
                change="Active learners"
                changeType="positive"
              />
              <StatCard
                title="Faculty & Staff"
                value={metrics.totalFaculty.toLocaleString()}
                icon={GraduationCap}
                iconColor="#10B981"
                change="Active on duty"
                changeType="positive"
              />
              <StatCard
                title="Today's Attendance"
                value={`${metrics.attendanceRate}%`}
                icon={Calendar}
                iconColor="#3B82F6"
                change="Real-time check-in"
                changeType="positive"
              />
              <StatCard
                title="Fee Realization Rate"
                value={`${metrics.collectionRate}%`}
                icon={CreditCard}
                iconColor="#10B981"
                change="On track"
                changeType="positive"
              />
            </View>

            {/* Quick Summary Card */}
            <View style={styles.summaryCard}>
              <View style={styles.summaryCardHeader}>
                <View style={styles.cardHeaderIconBox}>
                  <BarChart3 size={20} color="#D97706" {...({} as any)} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.summaryCardTitle}>Executive Performance Snapshot</Text>
                  <Text style={styles.summaryCardSubtitle}>Summary metrics and key health indicators</Text>
                </View>
              </View>

              {/* 4 Colored Highlight Tiles */}
              <View style={styles.highlightTilesGrid}>
                <View style={[styles.highlightTile, { backgroundColor: '#ECFDF5', borderColor: '#A7F3D0' }]}>
                  <Text style={styles.highlightTileLabel}>Revenue Collected</Text>
                  <Text style={[styles.highlightTileValue, { color: '#059669' }]}>
                    {formatCurrency(metrics.totalFeeCollected)}
                  </Text>
                </View>
                <View style={[styles.highlightTile, { backgroundColor: '#FEF2F2', borderColor: '#FECACA' }]}>
                  <Text style={styles.highlightTileLabel}>Outstanding Dues</Text>
                  <Text style={[styles.highlightTileValue, { color: '#DC2626' }]}>
                    {formatCurrency(metrics.totalFeePending)}
                  </Text>
                </View>
                <View style={[styles.highlightTile, { backgroundColor: '#FFFBEB', borderColor: '#FDE68A' }]}>
                  <Text style={styles.highlightTileLabel}>Academic Rating</Text>
                  <Text style={[styles.highlightTileValue, { color: '#B45309' }]}>
                    {metrics.averageGrade} ({metrics.passPercentage}%)
                  </Text>
                </View>
                <View style={[styles.highlightTile, { backgroundColor: '#EFF6FF', borderColor: '#BFDBFE' }]}>
                  <Text style={styles.highlightTileLabel}>Student-Faculty Ratio</Text>
                  <Text style={[styles.highlightTileValue, { color: '#2563EB' }]}>
                    {metrics.totalFaculty > 0 ? `${Math.round(metrics.totalStudents / metrics.totalFaculty)} : 1` : '18 : 1'}
                  </Text>
                </View>
              </View>

              <View style={styles.summaryDivider} />

              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Institutions in Scope</Text>
                <Text style={styles.summaryValue}>{linkedInstitutions.length || 1}</Text>
              </View>
              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Total Annual Target</Text>
                <Text style={styles.summaryValue}>{formatCurrency(metrics.totalFeeExpected)}</Text>
              </View>
              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Accreditation & Compliance Status</Text>
                <View style={styles.complianceChip}>
                  <CheckCircle size={12} color="#059669" {...({} as any)} />
                  <Text style={styles.complianceChipText}>Fully Compliant</Text>
                </View>
              </View>
            </View>

            {/* Read-Only Notice on Action Buttons */}
            <View style={styles.actionNoticeCard}>
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                <ShieldCheck size={18} color="#D97706" {...({} as any)} />
                <Text style={styles.actionNoticeTitle}>Administrative Actions Protected (RBAC)</Text>
              </View>
              <Text style={styles.actionNoticeDesc}>
                Stakeholders have cryptographic read-only privileges. Creation, modification, and deletion of records are restricted to Institution Admins, Accountants, and Faculty.
              </Text>
              <View style={styles.testButtonsRow}>
                <TouchableOpacity
                  style={styles.disabledActionButton}
                  activeOpacity={0.7}
                  onPress={() => handleAttemptWrite('Create Student')}
                >
                  <Text style={styles.disabledActionButtonText}>+ Add Student (Restricted)</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={styles.disabledActionButton}
                  activeOpacity={0.7}
                  onPress={() => handleAttemptWrite('Modify Fee Structure')}
                >
                  <Text style={styles.disabledActionButtonText}>✏️ Edit Fee (Restricted)</Text>
                </TouchableOpacity>
              </View>
            </View>
          </View>
        )}

        {/* TAB 2: FINANCIALS */}
        {activeTab === 'financials' && (
          <View style={styles.tabContent}>
            <Text style={styles.sectionHeader}>Treasury & Financial Health</Text>
            
            <View style={styles.statsGrid}>
              <StatCard
                title="Revenue (YTD)"
                value={formatCurrency(metrics.totalFeeCollected)}
                icon={TrendingUp}
                iconColor="#10B981"
                change="Real-time collection"
                changeType="positive"
              />
              <StatCard
                title="Outstanding Dues"
                value={formatCurrency(metrics.totalFeePending)}
                icon={Clock}
                iconColor="#EF4444"
                change="Follow-up active"
                changeType="negative"
              />
              <StatCard
                title="Annual Budget Expected"
                value={formatCurrency(metrics.totalFeeExpected)}
                icon={DollarSign}
                iconColor="#3B82F6"
                change="FY 2026-27 Target"
              />
              <StatCard
                title="Realization Rate"
                value={`${metrics.collectionRate}%`}
                icon={CreditCard}
                iconColor="#F59E0B"
                change="Target: 95%"
                changeType="positive"
              />
            </View>

            {/* Annual Fee Progress Card */}
            <View style={styles.financeCard}>
              <View style={styles.summaryCardHeader}>
                <View style={styles.cardHeaderIconBox}>
                  <DollarSign size={20} color="#D97706" {...({} as any)} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.financeCardTitle}>Annual Fee Collection Progress</Text>
                  <Text style={styles.financeCardSubtitle}>Overall revenue realization against budgeted fee schedule</Text>
                </View>
              </View>

              <View style={styles.progressBarContainer}>
                <View style={[styles.progressBarFill, { width: `${Math.min(metrics.collectionRate, 100)}%` }]} />
              </View>
              <View style={styles.progressLabelRow}>
                <Text style={styles.progressSubtext}>Realization Progress</Text>
                <Text style={styles.progressText}>{metrics.collectionRate}% Collected</Text>
              </View>

              <View style={styles.financeBreakdown}>
                <View style={styles.financeItem}>
                  <Text style={styles.financeItemLabel}>Total Expected</Text>
                  <Text style={styles.financeItemValue}>{formatCurrency(metrics.totalFeeExpected)}</Text>
                </View>
                <View style={styles.financeItem}>
                  <Text style={styles.financeItemLabel}>Collected (YTD)</Text>
                  <Text style={[styles.financeItemValue, { color: '#059669' }]}>
                    {formatCurrency(metrics.totalFeeCollected)}
                  </Text>
                </View>
                <View style={styles.financeItem}>
                  <Text style={styles.financeItemLabel}>Pending Dues</Text>
                  <Text style={[styles.financeItemValue, { color: '#DC2626' }]}>
                    {formatCurrency(metrics.totalFeePending)}
                  </Text>
                </View>
              </View>
            </View>

            {/* Category Breakdown Card */}
            <View style={styles.financeCard}>
              <Text style={styles.subSectionTitle}>Revenue Category Breakdown</Text>
              
              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Tuition & Academic Fees</Text>
                  <Text style={styles.categoryPercent}>88% Collected</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '88%', backgroundColor: '#10B981' }]} />
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Transport & Fleet Logistics</Text>
                  <Text style={styles.categoryPercent}>94% Collected</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '94%', backgroundColor: '#3B82F6' }]} />
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Examinations & Laboratory</Text>
                  <Text style={styles.categoryPercent}>96% Collected</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '96%', backgroundColor: '#F59E0B' }]} />
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Sports, Library & Activities</Text>
                  <Text style={styles.categoryPercent}>82% Collected</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '82%', backgroundColor: '#8B5CF6' }]} />
                </View>
              </View>
            </View>
          </View>
        )}

        {/* TAB 3: ACADEMICS & QUALITY ASSURANCE */}
        {activeTab === 'academics' && (
          <View style={styles.tabContent}>
            <Text style={styles.sectionHeader}>Academics & Quality Assurance</Text>
            
            {/* StatCards for Academics */}
            <View style={styles.statsGrid}>
              <StatCard
                title="Academic Pass Rate"
                value={`${metrics.passPercentage}%`}
                icon={Award}
                iconColor="#10B981"
                change="Standardized testing"
                changeType="positive"
              />
              <StatCard
                title="Average Grade"
                value={metrics.averageGrade}
                icon={GraduationCap}
                iconColor="#F59E0B"
                change="Above regional avg"
                changeType="positive"
              />
              <StatCard
                title="Student Attendance"
                value={`${metrics.attendanceRate}%`}
                icon={Users}
                iconColor="#3B82F6"
                change="Term-to-date average"
                changeType="positive"
              />
              <StatCard
                title="Faculty Attendance"
                value="98.2%"
                icon={UserCheck}
                iconColor="#10B981"
                change="On schedule"
                changeType="positive"
              />
            </View>

            {/* Standardized Academic Excellence Rating Card */}
            <View style={styles.academicCard}>
              <View style={styles.academicHeader}>
                <View style={styles.cardHeaderIconBox}>
                  <Award size={22} color="#D97706" {...({} as any)} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.academicTitle}>Overall Academic Performance Index</Text>
                  <Text style={styles.academicSubtitle}>Standardized term assessments across all grades & sections</Text>
                </View>
              </View>

              <View style={styles.gradeBadgeContainer}>
                <View style={styles.gradeBadge}>
                  <Text style={styles.gradeBadgeText}>{metrics.averageGrade}</Text>
                </View>
                <View style={{ flex: 1, marginLeft: 16 }}>
                  <Text style={styles.academicStatTitle}>Pass Rate: {metrics.passPercentage}%</Text>
                  <Text style={styles.academicStatDesc}>
                    Average across all classes, sections, and term examinations. Outperforming state benchmark by +4.8%.
                  </Text>
                </View>
              </View>

              {/* Examination Series Milestones */}
              <View style={styles.examMilestonesRow}>
                <View style={styles.examMilestoneItem}>
                  <View style={styles.examMilestoneDot} />
                  <Text style={styles.examMilestoneTitle}>Term 1 Series</Text>
                  <Text style={styles.examMilestoneStatus}>Completed (93.4%)</Text>
                </View>
                <View style={styles.examMilestoneItem}>
                  <View style={styles.examMilestoneDot} />
                  <Text style={styles.examMilestoneTitle}>Midterm Series</Text>
                  <Text style={styles.examMilestoneStatus}>Completed (95.1%)</Text>
                </View>
                <View style={styles.examMilestoneItem}>
                  <View style={[styles.examMilestoneDot, { backgroundColor: '#F59E0B' }]} />
                  <Text style={styles.examMilestoneTitle}>Term 2 Finals</Text>
                  <Text style={[styles.examMilestoneStatus, { color: '#F59E0B' }]}>Scheduled</Text>
                </View>
              </View>
            </View>

            {/* Subject Groups Performance */}
            <View style={styles.academicCard}>
              <View style={styles.academicHeader}>
                <View style={styles.cardHeaderIconBox}>
                  <BookOpen size={20} color="#D97706" {...({} as any)} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.academicTitle}>Departmental Mastery & Subject Grouping</Text>
                  <Text style={styles.academicSubtitle}>Assessment scores categorized by discipline</Text>
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Science & Technology (STEM)</Text>
                  <Text style={styles.categoryPercent}>92% Pass Rate</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '92%', backgroundColor: '#10B981' }]} />
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Mathematics & Logical Reasoning</Text>
                  <Text style={styles.categoryPercent}>88% Pass Rate</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '88%', backgroundColor: '#F59E0B' }]} />
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Languages & Literature</Text>
                  <Text style={styles.categoryPercent}>96% Pass Rate</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '96%', backgroundColor: '#3B82F6' }]} />
                </View>
              </View>

              <View style={styles.categoryItem}>
                <View style={styles.categoryHeader}>
                  <Text style={styles.categoryName}>Social Sciences & Humanities</Text>
                  <Text style={styles.categoryPercent}>91% Pass Rate</Text>
                </View>
                <View style={styles.smallProgressBg}>
                  <View style={[styles.smallProgressFill, { width: '91%', backgroundColor: '#8B5CF6' }]} />
                </View>
              </View>
            </View>

            {/* Accreditation & Institutional Quality */}
            <View style={styles.academicCard}>
              <View style={styles.academicHeader}>
                <View style={styles.cardHeaderIconBox}>
                  <School size={20} color="#D97706" {...({} as any)} />
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={styles.academicTitle}>Accreditation & Quality Standards</Text>
                  <Text style={styles.academicSubtitle}>Regulatory compliance and teacher ratio standards</Text>
                </View>
              </View>

              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Student-to-Teacher Ratio</Text>
                <Text style={styles.summaryValue}>
                  {metrics.totalFaculty > 0 ? `${Math.round(metrics.totalStudents / metrics.totalFaculty)} : 1` : '18 : 1'} (Optimal &lt; 25:1)
                </Text>
              </View>
              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Active Classrooms & Labs</Text>
                <Text style={styles.summaryValue}>32 Sections Operational</Text>
              </View>
              <View style={styles.summaryRow}>
                <Text style={styles.summaryLabel}>Institutional Board Rating</Text>
                <Text style={[styles.summaryValue, { color: '#059669' }]}>Grade A+ Accredited</Text>
              </View>
            </View>
          </View>
        )}

        {/* TAB 4: INSTITUTION COMPARISON */}
        {activeTab === 'institutions' && (
          <View style={styles.tabContent}>
            <Text style={styles.sectionHeader}>Institution Benchmarks</Text>
            {institutionBreakdown.map((item) => (
              <View key={item.institution_id} style={styles.comparisonCard}>
                <View style={styles.comparisonHeader}>
                  <Building2 size={18} color={theme.colors.secondary} {...({} as any)} />
                  <Text style={styles.comparisonName}>{item.institution_name}</Text>
                </View>
                <View style={styles.comparisonGrid}>
                  <View style={styles.comparisonItem}>
                    <Text style={styles.comparisonLabel}>Students</Text>
                    <Text style={styles.comparisonValue}>{item.student_count}</Text>
                  </View>
                  <View style={styles.comparisonItem}>
                    <Text style={styles.comparisonLabel}>Faculty</Text>
                    <Text style={styles.comparisonValue}>{item.staff_count}</Text>
                  </View>
                  <View style={styles.comparisonItem}>
                    <Text style={styles.comparisonLabel}>Attendance</Text>
                    <Text style={styles.comparisonValue}>{item.attendance_percentage}%</Text>
                  </View>
                  <View style={styles.comparisonItem}>
                    <Text style={styles.comparisonLabel}>Revenue</Text>
                    <Text style={[styles.comparisonValue, { color: '#059669' }]}>
                      {formatCurrency(item.total_revenue_collected)}
                    </Text>
                  </View>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* Footer & Sign Out */}
        <View style={styles.footerContainer}>
          <Text style={styles.footerCopyright}>My Vidyon ERP • Board of Trustees Governance Suite</Text>
          <TouchableOpacity style={styles.signOutButton} onPress={signOut} activeOpacity={0.8}>
            <Text style={styles.signOutButtonText}>Sign Out</Text>
          </TouchableOpacity>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background, // Warm beige #F8F9F3
  },
  contentContainer: {
    padding: 24,
    paddingBottom: 60,
  },
  responsiveContainer: {
    width: '100%',
    maxWidth: 1200,
    alignSelf: 'center',
  },
  headerActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  liveBadge: {
    backgroundColor: '#10B98115',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#10B98130',
  },
  liveBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#10B981',
    letterSpacing: 0.4,
  },
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: theme.colors.primary, // #FAB75A Vidyon signature warm gold
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  exportButtonText: {
    color: '#1E293B',
    fontWeight: '700',
    fontSize: 13,
  },
  bannerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB', // Warm amber tint
    borderColor: '#FDE68A',
    borderWidth: 1,
    borderRadius: 20,
    marginBottom: 20,
    padding: 16,
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  bannerIconWrapper: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerTextContainer: {
    flex: 1,
  },
  bannerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#92400E',
  },
  bannerSubtitle: {
    fontSize: 12,
    color: '#B45309',
    marginTop: 2,
    lineHeight: 17,
  },
  viewBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#FEF3C7',
    borderColor: '#FDE68A',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  viewBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#92400E',
    letterSpacing: 0.5,
  },
  selectorCard: {
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  selectorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  selectorLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.textMuted,
    letterSpacing: 0.5,
  },
  selectorDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8F9F3',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
  },
  selectorIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorCurrentText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text,
  },
  dropdownMenu: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingTop: 8,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  dropdownItemActive: {
    backgroundColor: '#FEF3C7',
  },
  dropdownItemText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '500',
  },
  dropdownItemTextActive: {
    color: '#92400E',
    fontWeight: '700',
  },
  tabsRow: {
    flexDirection: 'row',
    marginBottom: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 5,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
    gap: 6,
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 14,
  },
  tabButtonActive: {
    backgroundColor: theme.colors.primary, // #FAB75A
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.textMuted,
  },
  tabButtonTextActive: {
    color: '#1E293B',
    fontWeight: '700',
  },
  tabContent: {
    width: '100%',
  },
  sectionHeader: {
    fontSize: 17,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 16,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  cardHeaderIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#FEF3C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  summaryCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text,
  },
  summaryCardSubtitle: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  highlightTilesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  highlightTile: {
    flex: 1,
    minWidth: '45%',
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
  },
  highlightTileLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.textMuted,
    marginBottom: 4,
  },
  highlightTileValue: {
    fontSize: 16,
    fontWeight: '800',
  },
  summaryDivider: {
    height: 1,
    backgroundColor: '#F8F9F3',
    marginVertical: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F8FAFC',
  },
  summaryLabel: {
    fontSize: 13,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.text,
  },
  complianceChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  complianceChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#059669',
  },
  actionNoticeCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#FDE68A',
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  actionNoticeTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#92400E',
  },
  actionNoticeDesc: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginBottom: 16,
    lineHeight: 18,
  },
  testButtonsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  disabledActionButton: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  disabledActionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#94A3B8',
  },
  financeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  financeCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text,
  },
  financeCardSubtitle: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  progressBarContainer: {
    height: 12,
    backgroundColor: '#F1F5F9',
    borderRadius: 6,
    overflow: 'hidden',
    marginTop: 18,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.accent, // #10B981 emerald
  },
  progressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  progressSubtext: {
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  progressText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.accent,
  },
  financeBreakdown: {
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#F8F9F3',
    paddingTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  financeItem: {
    flex: 1,
    alignItems: 'center',
  },
  financeItemLabel: {
    fontSize: 11,
    color: theme.colors.textMuted,
    marginBottom: 4,
    fontWeight: '500',
  },
  financeItemValue: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.text,
  },
  subSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: 16,
  },
  categoryItem: {
    marginBottom: 14,
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  categoryName: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.text,
  },
  categoryPercent: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.textMuted,
  },
  smallProgressBg: {
    height: 8,
    backgroundColor: '#F1F5F9',
    borderRadius: 4,
    overflow: 'hidden',
  },
  smallProgressFill: {
    height: '100%',
    borderRadius: 4,
  },
  academicCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  academicHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 18,
  },
  academicTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text,
  },
  academicSubtitle: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  gradeBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#FDE68A',
    marginBottom: 16,
  },
  gradeBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.primary, // Signature warm gold #FAB75A
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  gradeBadgeText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1E293B',
  },
  academicStatTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#92400E',
  },
  academicStatDesc: {
    fontSize: 12,
    color: '#B45309',
    marginTop: 4,
    lineHeight: 18,
  },
  examMilestonesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F8F9F3',
  },
  examMilestoneItem: {
    flex: 1,
    alignItems: 'center',
  },
  examMilestoneDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
    marginBottom: 6,
  },
  examMilestoneTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.text,
  },
  examMilestoneStatus: {
    fontSize: 10,
    color: '#10B981',
    fontWeight: '600',
    marginTop: 2,
  },
  comparisonCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  comparisonHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F8F9F3',
    paddingBottom: 12,
  },
  comparisonName: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.colors.text,
  },
  comparisonGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  comparisonItem: {
    alignItems: 'center',
  },
  comparisonLabel: {
    fontSize: 11,
    color: theme.colors.textMuted,
    marginBottom: 4,
  },
  comparisonValue: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.text,
  },
  footerContainer: {
    marginTop: 24,
    marginBottom: 16,
    alignItems: 'center',
    gap: 12,
  },
  footerCopyright: {
    fontSize: 12,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  signOutButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    alignItems: 'center',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  signOutButtonText: {
    color: theme.colors.textMuted,
    fontWeight: '600',
    fontSize: 14,
  },
});
